# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c81bfb6679c279d77d1c5d62caeaa1b31b8a7bfaefb161d3d46d64230696d690bc75bd3422b0fb9dff99e094d3af3189232bf79fd72c251a1368c4664ec1d0bf

test:
  secret_key_base: 1a1412bce352b86e515f8b6c3a8cd05251022a17e974256fcac50b6a0eb0e5ec21ff81fdaee22d6628e6cfee88d511ea1c2c709a70bf1b8a875a54df2e0721d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
